// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Jya4N3ibOW8OHsae6Y4YFfFa0j6fMVA',
    appId: '1:596371943525:web:ebb106c703f1e5e106d68c',
    messagingSenderId: '596371943525',
    projectId: 'bmi-task-21fcd',
    authDomain: 'bmi-task-21fcd.firebaseapp.com',
    storageBucket: 'bmi-task-21fcd.appspot.com',
    measurementId: 'G-TMV111QVPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHQmZSXoFaLJOFjKAa8Dcf_3QUsB3Ot1w',
    appId: '1:596371943525:android:6fc9f4ec4934fc8c06d68c',
    messagingSenderId: '596371943525',
    projectId: 'bmi-task-21fcd',
    storageBucket: 'bmi-task-21fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPdEiEqYnlyNgtn4sKg4BoYcloHPxCmg',
    appId: '1:596371943525:ios:b23bb397cd874d7706d68c',
    messagingSenderId: '596371943525',
    projectId: 'bmi-task-21fcd',
    storageBucket: 'bmi-task-21fcd.appspot.com',
    iosBundleId: 'com.example.bmiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqPdEiEqYnlyNgtn4sKg4BoYcloHPxCmg',
    appId: '1:596371943525:ios:b23bb397cd874d7706d68c',
    messagingSenderId: '596371943525',
    projectId: 'bmi-task-21fcd',
    storageBucket: 'bmi-task-21fcd.appspot.com',
    iosBundleId: 'com.example.bmiTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Jya4N3ibOW8OHsae6Y4YFfFa0j6fMVA',
    appId: '1:596371943525:web:b18ddea8e02990d306d68c',
    messagingSenderId: '596371943525',
    projectId: 'bmi-task-21fcd',
    authDomain: 'bmi-task-21fcd.firebaseapp.com',
    storageBucket: 'bmi-task-21fcd.appspot.com',
    measurementId: 'G-C8WBE7MQ11',
  );

}